![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [2]:
import numpy as np
np.__version__

'2.2.5'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [4]:
my_array = np.arange(0,10,1)
print(my_array)


[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [9]:
array = np.array([[True,True,True],[True,True,True],[True,True,True]])
print(array)


"""
np.full función para crear matrices 
array = np.full((3,3),True)
no.full((3,3),True).reshape(3,-1) el -1 toma el valor de 3
print(array)"""

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


'\nnp.full función para crear matrices \narray = np.full((3,3),True)\nno.full((3,3),True).reshape(3,-1) el -1 toma el valor de 3\nprint(array)'

## Ejercicio 4
Extrae todos los impares de `my_array`

In [ ]:
for impares in my_array:
    if impares%2 !=0:
        print (impares)

"""Con máscara: las máscaras siempre serán booleanos
    mask = my_array%2 != 0
    my_array[mask]
"""

1
3
5
7
9


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [ ]:
nuevo_array = my_array.copy()
condicion = my_array % 2 != 0
nuevo_array[condicion] = -1

print (nuevo_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [ ]:

# Condición, que quiero si se cumple (TRUE), y que quiero sino se cumple (FALSE)
np.where(my_array % 2 != 0, -1,my_array)



array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [48]:
nuevo_array = np.reshape(my_array,(2,5))
print(nuevo_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)


np.concatenate((a,b))
# Pq en tupla o en lista para poder meter todos los números que queramos y que no nos dé problemas


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [61]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)


np.concatenate((a,b),axis = 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [65]:

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [67]:
np.concatenate.__doc__

'\n    concatenate(\n        (a1, a2, ...),\n        axis=0,\n        out=None,\n        dtype=None,\n        casting="same_kind"\n    )\n\n    Join a sequence of arrays along an existing axis.\n\n    Parameters\n    ----------\n    a1, a2, ... : sequence of array_like\n        The arrays must have the same shape, except in the dimension\n        corresponding to `axis` (the first, by default).\n    axis : int, optional\n        The axis along which the arrays will be joined.  If axis is None,\n        arrays are flattened before use.  Default is 0.\n    out : ndarray, optional\n        If provided, the destination to place the result. The shape must be\n        correct, matching that of what concatenate would have returned if no\n        out argument were specified.\n    dtype : str or dtype\n        If provided, the destination array will have this dtype. Cannot be\n        provided together with `out`.\n\n        .. versionadded:: 1.20.0\n\n    casting : {\'no\', \'equiv\', \'safe\'

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [20]:
my_array = np.array([0,1,2,3,4,5,6,7,8,9])
print(my_array*10)
print(my_array[0])
print(my_array[-1])
print(my_array[1:8:1]) #start stop step


[ 0 10 20 30 40 50 60 70 80 90]
0
9
[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [ ]:
my_matrix = np.array(
    [[1,2,3],
    [4,5,6],
    [7,8,9]])


(3, 3)


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [75]:
print(np.arange(1, 50, 3))

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [80]:
print(np.arange(4, 1, -0.25))

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

In [ ]:
import matplotlib.pyplot   as plt

imagen = plt.imread("")
print(type(imagen))
print(imagen.shape)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [ ]:
array = np.array([[1],[2],[3],[4]])
print(array.shape)
nuevo_array = np.reshape(array,(2,2))
print(nuevo_array)

(4, 1)
[[1 2]
 [3 4]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [100]:
print(np.random.randint(10, size = (4,5,3)))



[[[9 0 4]
  [0 5 4]
  [5 4 8]
  [6 3 0]
  [1 9 7]]

 [[9 9 4]
  [1 5 3]
  [1 4 5]
  [1 2 9]
  [9 9 9]]

 [[4 8 8]
  [3 2 8]
  [7 8 2]
  [6 7 2]
  [9 8 0]]

 [[4 4 6]
  [5 6 2]
  [3 0 1]
  [4 9 5]
  [6 6 2]]]


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [111]:
matriz_10x1 = np.full((10, 1), False)
matriz_2x5 = np.reshape(matriz_10x1, (2, 5))
print(matriz_2x5)

[[False False False False False]
 [False False False False False]]


## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [120]:
x =np.random.randint(10, 20, size = (5,2,6))

print(x.shape)
print("Número de elementos: 5" )
print("Número dimensiones:",x.ndim)
print("Cada dimensión tiene 2*6 elementos")

(5, 2, 6)
Número de elementos: 5
Número dimensiones: 3
Cada dimensión tiene 2*6 elementos
