![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

my_array = np.arange(0,10)
print(my_array[:-10:-2])


[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [ ]:
print(my_array[-2:-4:-1])

# my_array[[8,7]]

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [3]:
print(my_array[-8:-11:-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [7]:
matrix_4x5 = np.array(
            [[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]]) 

print(matrix_4x5[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [8]:
print(matrix_4x5[:2,:2])

[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [9]:

print(matrix_4x5[::2,::2])

[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [10]:

print(matrix_4x5[:3,::-1])

[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [95]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

mask = x == "Loro"

print(x[mask])

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [105]:
secuencia = np.arange(0,20)

secuencia.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [110]:

print(matrix_4x5[::-1,::-1])

[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [13]:
array = np.zeros(10)
array.nbytes

array[3] =1
print(array)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [125]:
vector = np.arange(10,50)
print(vector[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [137]:
vector = np.array([1,2,0,0,4,0])

indices = np.where(vector !=0 )
print (indices)

(array([0, 1, 4]),)


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [143]:
matriz_10x10 = np.arange(0,100).reshape(10,10)
print(matriz_10x10)

num_max = np.max(matriz_10x10)
num_min = np.min(matriz_10x10)
print(f"El número máximo es {num_max} y el mínimo {num_min}")

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
El número máximo es 99 y el mínimo 0


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [27]:
array = np.random.rand(10,10)

array.mean()


np.float64(0.5382057769079023)

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [ ]:
array = np.ones((10,10))
array[1:-1,1:-1] = 0
print(array)



[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [ ]:
array = ([])

for i in range(8):
    for j in range(8):
        if (i+j)%2 !=0:
            array[i,j] = 1
    

TypeError: list indices must be integers or slices, not tuple

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [44]:
patron = np.array([[0,1],[1,0]])
np.tile(patron,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [174]:
matriz_5x5 = np.arange(0,25).reshape(5,5)

media = np.mean(matriz_5x5)
desviacion_estandar = np.std(matriz_5x5)
matriz_normalizada = ((matriz_5x5 - media)/(desviacion_estandar))
print(matriz_normalizada)
       

[[-1.66410059 -1.52542554 -1.38675049 -1.24807544 -1.10940039]
 [-0.97072534 -0.83205029 -0.69337525 -0.5547002  -0.41602515]
 [-0.2773501  -0.13867505  0.          0.13867505  0.2773501 ]
 [ 0.41602515  0.5547002   0.69337525  0.83205029  0.97072534]
 [ 1.10940039  1.24807544  1.38675049  1.52542554  1.66410059]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [182]:
secuencia_num = np.arange(0,11)

secuencia_num[4:8] = -1
print(secuencia_num)

[ 0  1  2  3 -1 -1 -1 -1  8  9 10]


## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [ ]:
tablero = np.full((10,10)," ")

def disparar (fila,columna):

    if tablero[fila,columna] == "O":
        tablero[fila,columna] = "X"
        print("Tocado")
    elif tablero[fila,columna] == "X":
        print("Barco ya tocado")
    else:
        tablero[fila,columna] = "A"
        print("Agua")
    return tablero

tablero[0:2,1] = "O"
tablero[1,3:7] = "O"

#Barcos aleatorios

def generar_barcos (eslora,orientacion,coord1,coord2):

    # En función de la orientación dibujar las coordenadas
    # tablero[coord1 - eslora:-1, coord2] en N y S tablero[coord1 + eslora: 1, coord2]
    # tablero[coord1, coord2 -eslora:-1] en E y O tablero[coord1, coord2+ eslora: 1]


In [5]:
import numpy as np


class Tablero:
  def __init__(self, id_jugador, dimensiones):
    self.id_jugador = id_jugador
    self.dimensiones = dimensiones
    self.tablero = np.full((10,10), " ")
    self.eslora = np.random.choice([1,2,3,4])
    self.trenes =  {
    "tren 1":1,
    "tren 2":2,
    "tren 3":3,
    "tren 4":4
}

  def inicializar_tablero(self):
    return self.tablero

# R = Renfe, B = Bombardeado y T = Tierra
  def disparar(self,coord_fila,coord_col):
    if coord_fila < 0 or coord_fila >= len(self.tablero) or coord_col < 0 or coord_col >= len(self.tablero):
      print("Disparo fuera del tablero")
    elif self.tablero[coord_fila,coord_col] == "R":
      self.tablero[coord_fila,coord_col] = "B"
      print("Bombardeado")
    elif self.tablero[coord_fila,coord_col] == "B" or self.tablero[coord_fila,coord_col] == "T":
      print("Tren ya tocado")
    else:
      self.tablero[coord_fila,coord_col] = "T"
      print("Tierra")

  def pedir_coordenadas (self):
    coord_fila = int(input("Introduce la fila"))
    coord_columna = int(input("Introduce la columna"))
    self.disparar(coord_fila,coord_columna)


  def colocar_trenes(self):
        # Colocamos los trenes uno por uno
        for eslora, cantidad in self.trenes.items():
            for i in range(cantidad):  # Colocamos la cantidad de trenes según su eslora
                colocado = False
                while not colocado:
                    # Elegimos una orientación y coordenadas aleatorias
                    orientacion = np.random.choice(["V", "H"])
                    coord1 = np.random.randint(0, 10)
                    coord2 = np.random.randint(0, 10)

                    # Intentamos colocar el tren en la posición
                    if orientacion == "V" and coord1 + eslora <= 10:  # Si es vertical y cabe
                        if np.all(self.tablero[coord1:coord1+eslora, coord2] == " "):  # Verificamos que esté vacío
                            self.tablero[coord1:coord1+eslora, coord2] = "R"  # Colocamos el tren
                            colocado = True
                    elif orientacion == "H" and coord2 + eslora <= 10:  # Si es horizontal y cabe
                        if np.all(self.tablero[coord1, coord2:coord2+eslora] == " "):  # Verificamos que esté vacío
                            self.tablero[coord1, coord2:coord2+eslora] = "R"  # Colocamos el tren
                            colocado = True

        return print(self.tablero)

In [7]:
#PRUEBBAS
tablero = Tablero("Jugador 1", (10,10))
tablero.inicializar_tablero()
tablero.colocar_trenes()


TypeError: unsupported operand type(s) for +: 'int' and 'str'